# Generated by Django 2.2.5 on 2019-09-23 11:11
# Check https://docs.djangoproject.com/en/2.2/ref/migration-operations/#runpython

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Category = apps.get_model("api", "Category")
    SubCategory = apps.get_model("api", "SubCategory")
    db_alias = schema_editor.connection.alias

    Category.objects.using(db_alias).bulk_create([
        Category(name="Informática", description="Material de aprendizaje sobre informática"),
        Category(name="Matemáticas", description="Material de aprendizaje sobre matemáticas"),
        Category(name="Inglés", description="Material de aprendizaje sobre inglés"),
    ])

    cat1 = Category.objects.get(name="Informática")
    cat2 = Category.objects.get(name="Matemáticas")
    cat3 = Category.objects.get(name="Inglés")

    SubCategory.objects.using(db_alias).bulk_create([
        SubCategory(category=cat1, name="Desarrollo web", description="Material de aprendizaje sobre desarrollo web"),
        SubCategory(category=cat1, name="Bases de datos", description="Material de aprendizaje sobre bases de datos"),
        SubCategory(category=cat1, name="DevOps", description="Material de aprendizaje sobre cultura DevOps"),
        SubCategory(category=cat2, name="Álgebra", description="Material de aprendizaje sobre álgebra"),
        SubCategory(category=cat2, name="Cálculo", description="Material de aprendizaje sobre cálculo"),
        SubCategory(category=cat3, name="Básico", description="Material de aprendizaje básico de inglés"),
        SubCategory(category=cat3, name="Avanzado", description="Material de aprendizaje avanzado de inglés")
    ])

def reverse_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Category = apps.get_model("api", "Category")
    db_alias = schema_editor.connection.alias

    Category.objects.using(db_alias).filter(name__in=["Informática", "Matemáticas", "Inglés"]).delete()

    # No need to delete subcategories, because cascade

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
