# Generated by Django 2.2.5 on 2019-09-25 22:47

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Category = apps.get_model("api", "Category")
    SubCategory = apps.get_model("api", "SubCategory")
    Product = apps.get_model("api", "Product")
    db_alias = schema_editor.connection.alias

    Category.objects.using(db_alias).bulk_create([
        Category(name="Informática", description="Material de aprendizaje sobre informática"),
        Category(name="Matemáticas", description="Material de aprendizaje sobre matemáticas"),
        Category(name="Inglés", description="Material de aprendizaje sobre inglés"),
    ])

    cat1 = Category.objects.get(name="Informática")
    cat2 = Category.objects.get(name="Matemáticas")
    cat3 = Category.objects.get(name="Inglés")

    SubCategory.objects.using(db_alias).bulk_create([
        SubCategory(category=cat1, name="Desarrollo web", description="Material de aprendizaje sobre desarrollo web"),
        SubCategory(category=cat1, name="Bases de datos", description="Material de aprendizaje sobre bases de datos"),
        SubCategory(category=cat1, name="DevOps", description="Material de aprendizaje sobre cultura DevOps"),
        SubCategory(category=cat2, name="Álgebra", description="Material de aprendizaje sobre álgebra"),
        SubCategory(category=cat2, name="Cálculo", description="Material de aprendizaje sobre cálculo"),
        SubCategory(category=cat3, name="Básico", description="Material de aprendizaje básico de inglés"),
        SubCategory(category=cat3, name="Avanzado", description="Material de aprendizaje avanzado de inglés")
    ])

    subcat1 = SubCategory.objects.get(name="Bases de datos")
    subcat2 = SubCategory.objects.get(name="DevOps")
    subcat3 = SubCategory.objects.get(name="Álgebra")
    subcat4 = SubCategory.objects.get(name="Cálculo")

    Product.objects.using(db_alias).bulk_create([
        Product(subcategory=subcat1, name='PostgreSQL 10.0', description='PostgreSQL para pros', price=40),
        Product(subcategory=subcat2, name='Jenkins', description='Petalo con Jenkins', price=45),
        Product(subcategory=subcat3, name='Algebra para dummies', description='Aprende Álgebra desde cero', price=20),
        Product(subcategory=subcat3, name='Álgebra para pros', description='Álgebra para jefes', price=30),
        Product(subcategory=subcat4, name='Calculus II', description='La pesadilla de los estudiantes de ingenierías', price=100)
    ])


def reverse_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Category = apps.get_model("api", "Category")
    db_alias = schema_editor.connection.alias

    Category.objects.using(db_alias).filter(name__in=["Informática", "Matemáticas", "Inglés"]).delete()

    # No need to delete subcategories, because cascade

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
